/**
 * WhatsApp - the open source AUTOSAR platform https://github.com/parai
 *
 * Copyright (C) 2014  WhatsApp <parai@foxmail.com>
 *
 * This source code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 as published by the
 * Free Software Foundation; See <http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt>.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 * Version: AUTOSAR 4.2.0
 * Generated by arxml.py
 */
#ifndef ETHTRCV_TYPES_H
#define ETHTRCV_TYPES_H

/* ============================ [ INCLUDES  ] ====================================================== */
#include "Std_Types.h"
#ifdef __cplusplus
namespace autosar {
extern "C" {
#endif
/* ============================ [ MACROS    ] ====================================================== */
/* ============================ [ TYPES     ] ====================================================== */
/* Container for the references to DemEventParameter elements which shall be invoked using the
 *  API Dem_ReportErrorStatus API in case the corresponding error occurs. The EventId is taken
 *  from the referenced DemEventParameter's DemEventId value. The standardized errors are provided
 *  in the container and can be extended by vendor specific error references.
 */
typedef struct EthTrcv_DemEventParameterRefsType_tag
{
/* Reference to the DemEventParameter which shall be issued when the error "Transceiver access
 *  failed" has occured.
 */
/* /AUTOSAR/EcucDefs/Dem/DemConfigSet/DemEventParameter */
	Dem_EventParameterType* ETHTRCV_E_ACCESS ;
} EthTrcv_DemEventParameterRefsType ;

/* Configuration of the individual transceiver */
typedef struct EthTrcv_ConfigType_tag
{
	EthTrcv_DemEventParameterRefsType* EthTrcvDemEventParameterRefs ;
/* Specifies the controller used for MII access to the transceiver */
	uint8 EthTrcvCtrlIdx ;
/* Specifies the instance ID of the configured transceiver. */
	uint8 EthTrcvIdx ;
/* Specifies the transceiver index used for MII access to the transceiver */
	uint8 EthTrcvMiiIdx ;
} EthTrcv_ConfigType ;

/* All underlying parameters may be part of a multiple configuration set. */
typedef struct EthTrcv_ConfigSetType_tag
{
	EthTrcv_ConfigType* EthTrcvConfig ;
} EthTrcv_ConfigSetType ;

/* General configuration of Ethernet Transceiver Driver module */
typedef struct EthTrcv_GeneralType_tag
{
/* Enables / Disables development error detection */
	boolean EthTrcvDevErrorDetect ;
/* Enables / Disables EthTrcv_GetBaudRate API */
	boolean EthTrcvGetBaudRateApi ;
/* Enables / Disables EthTrcv_GetDuplexMode API */
	boolean EthTrcvGetDuplexModeApi ;
/* Enables / Disables EthTrcv_GetLinkState API */
	boolean EthTrcvGetLinkStateApi ;
/* Enables / Disables EthTrcv_GetTransceiverMode API */
	boolean EthTrcvGetTransceiverModeApi ;
/* Specifies the InstanceId of this module instance. If only one instance is present it shall have
 *  the Id 0.
 */
	uint8 EthTrcvIndex ;
	uint8 EthTrcvMaxTrcvsSupported ;
/* Enables / Disables EthTrcv_SetTransceiverMode API */
	boolean EthTrcvSetTransceiverModeApi ;
/* Enables / Disables EthTrcv_StartAutoNegotiation API */
	boolean EthTrcvStartAutoNegotiationApi ;
/* Enables / Disables version info API */
	boolean EthTrcvVersionInfoApi ;
/* Enables / Disables version info API macro implementation */
	boolean EthTrcvVersionInfoApiMacro ;
/* Wait count for transceiver state changes. */
	uint32 EthTrcvWaitCount ;
} EthTrcv_GeneralType ;

/* ============================ [ DATAS     ] ====================================================== */
/* ============================ [ DECLARES  ] ====================================================== */
/* ============================ [ LOCALS    ] ====================================================== */
/* ============================ [ FUNCTIONS ] ====================================================== */
#ifdef __cplusplus
}}  /* name space */
#endif
#endif /* ETHTRCV_TYPES_H */

